trajectory_step_s: 0.008
servo_control_cycle: 0.02
init_x_offset: 0.0
init_y_offset: 0.0
init_z_offset: 0.025
init_roll_offset: 0
init_pitch_offset: 0
init_yaw_offset: 0
hip_pitch_offset: 15
period_time: 1500
period_times: 0
dsp_ratio: 0.3
step_fb_ratio: 0.028
x_move_amplitude: 0.00
y_move_amplitude: 0.00
z_move_amplitude: 0.015
angle_move_amplitude: 0.0
y_swap_amplitude: 0.035
z_swap_amplitude: 0.006
pelvis_offset: 0
move_aim_on: False
arm_swing_gain: 0.0
